apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{_cursor_}}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: 
            command:
            - /bin/sh
            - -c
            - 
          restartPolicy: OnFailure

